name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      core: ${{ steps.changes.outputs.core }}
      nuxt: ${{ steps.changes.outputs.nuxt }}
    steps:
      - uses: actions/checkout@v5
      - uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            core:
              - 'package.json'
              - 'pnpm-lock.yaml'
              - 'pnpm-workspace.yaml'
              - 'src/**'
              - 'tsconfig.json'
              - 'tsconfig.app.json'
              - 'tsdown.config.ts'
              - 'vite.config.ts'
            nuxt:
              - 'apps/lism-ui-vue-nuxt/**'

  ci-core:
    name: Core CI
    needs: filter
    if: needs.filter.outputs.core == 'true' || github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: pnpmのセットアップ
        uses: pnpm/setup@v2
        with:
          version: 11
          install: false

      - name: Node.jsのセットアップ
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'pnpm'

      - name: 依存関係のインストール
        run: pnpm install

      - name: Lint の実行 (oxlint)
        run: pnpm lint:oxlint

      - name: 型チェックの実行
        run: pnpm type-check

      - name: テストの実行 (Vitest)
        run: pnpm run test

      - name: ビルドの実行
        run: pnpm build

  ci-nuxt:
    name: Nuxt CI
    needs: filter
    if: needs.filter.outputs.nuxt == 'true' || needs.filter.outputs.core == 'true' || github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: pnpmのセットアップ
        uses: pnpm/setup@v2
        with:
          version: 11
          install: false

      - name: Node.jsのセットアップ
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'pnpm'

      - name: 依存関係のインストール
        run: pnpm install

      - name: ビルドの実行
        run: pnpm build

      - name: Prepare Nuxt
        run: pnpm --filter @lism-ui-vue/nuxt run dev:prepare

      - name: 'Nuxtモジュール: テストの実行'
        run: pnpm --filter @lism-ui-vue/nuxt run test
